import { Playlist } from "./components/hooks/types";

export const playlists: Playlist[] = [
  {
    name: "Sorry )) It'$ too Late",
    id: 454036,
    Image: "2pac.jpg",
    songlist: [
      {
        id: 45401,
        name: "United In Grief",
        artist: "Kendrick Lamar",
        Image: "",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/griev.mp3",
      },
      {
        id: 45403,
        name: "Don't Go To Sleep",
        artist: "2pac",
        Image: "",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/Don't+Go+To+Sleep+-+2pac.mp3",
      },
    ],
  },
  {
    name: "ἀναγνώρισις",
    id: 947345,
    Image: "techno.jpg",
    songlist: [
      {
        id: 94730,
        name: "Chasing High",
        artist: "Héctor Oaks x",
        Image: "https://i.imgur.com/0MTvkvi.png",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/H%C3%A9ctor+Oaks+-+Chasing+Highs.mp3",
      },  
      {
        id: 94736,
        name: "Rigid",
        artist: "Rosa Anschütz",
        Image: "https://i.imgur.com/kWjkxN8.png",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/Rosa+Ansch%C3%BCtz+-+Rigid.mp3",
      },
      {
        id: 94737,
        name: "Love Story - The End",
        artist: "Beethoven",
        Image: "https://i.imgur.com/ioC4B69.png",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/Francis+Lai+-+Theme+From+Love+Story.mp3",
      },
      {
        id: 94733,
        name: "Hell on Earth",
        artist: "Kasst",
        Image: "https://i.imgur.com/36axOj2.png",
        number: "4",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/KAS_ST+-+Hell+On+Earth.mp3",
      },
      {
        id: 94732,
        name: "Insomnia",
        artist: "Kasst",
        Image: "https://i.imgur.com/7zqz7Qi.png",
        number: "5",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/KAS_ST+-+Insomnia.mp3",
      },
      {
        id: 94734,
        name: "A",
        artist: "Theme",
        Image: "https://i.imgur.com/dMamn6v.jpg",
        number: "6",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/Mello's+Theme.mp3",
      },
      {
        id: 94731,
        name: "Light",
        artist: "Death Note",
        Image: "https://i.imgur.com/dMamn6v.jpg",
        number: "7",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/Death+Note+-+Light's+Theme.mp3",
      },
      {
        id: 94735,
        name: "B",
        artist: "Theme",
        Image: "https://i.imgur.com/dMamn6v.jpg",
        number: "8",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/Mello's+Theme+B.mp3",
      },
    ],
  },
  {
    name: "",
    id: 795415,
    Image: "heart.jpg",
    songlist: [
      {
        id: 79541,
        name: "Instinct",
        artist: "",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Izzamuzzic+-+Instinct.mp3",
      },
      {
        id: 79542,
        name: "фразами к тебе ",
        artist: "Mania",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Mania+-+phrases+to+you.mp3",
      },
      {
        id: 79543,
        name: "Ты Не Королева",
        artist: "Artist",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/tinekaraleva.mp3"
      },
      {
        id: 79544,
        name: "Целуй меня",
        artist: "Мария Чайкоиская",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "4",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/kissme.mp3"
      },
      {
        id: 79545,
        name: "მე ყოველთვის მოგცემ",
        artist: "ლადო ნავერიანი",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "5",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/meyoveltvismogce.mp3"
      },
      {
        id: 79546,
        name: "გისველდება თმები",
        artist: "გიორგი ტიგინაშვილი",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "6",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Giorgi+Tiginashvili+++Gisveldeba+Tmebi.mp3"
      },
      {
        id: 79547,
        name: "♥",
        artist: "♥",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "7",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Sex+narkotiki.mp3"

      },
      {
        id: 79548,
        name: "Прятки",
        artist: "HammAli & Navai",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "8",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/HammAli+%26+Navai+-+pratki.mp3"
      },
      {
        id: 79549,
        name: "წუთებს დაკარგულს",
        artist: "ბალაბანი",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "9",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/dakarguliwutebi.mp3"
      },
      {
        id: 795410,
        name: "Листок",
        artist: "Xcho",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "10",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Xcho+-+listok.mp3"
      },
      {
        id: 795411,
        name: "მინდა რომ",
        artist: "Pajo",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "11",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/minda+rom.mp3"
      },
      {
        id: 795412,
        name: "ჩამეხუტე ♥",
        artist: "ს",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "12",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Chamexute+ra.mp3"
      },
      {
        id: 795413,
        name: "მომყევი გთხოვ",
        artist: "Pajo",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "13",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/momyevigtxov.mp3"
      },
      {
        id: 795414,
        name: "ასე თუ მტკიოდი ♥",
        artist: "Folk Bend",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "14",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/asetumtkiodi.mp3"
      },
      {
        id: 795415,
        name: "გიმღერი",
        artist: "Datuna alaphishvili",
        Image: "https://i.imgur.com/YMXYa0O.png",
        number: "15",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/unnamed/Gimgheri.mp3"
      },
    ],
  },
  {
    name: "Multiplatinum off Streets",
    id: 457897,
    Image: "guun.jpg",
    songlist: [
      {
        id: 45781,
        name: "No Complaints",
        artist: "Metro Boomin",
        Image: "",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/Metro+Boomin+-+No+Complaints.mp3",
      },
      {
        id: 45782,
        name: "Who Shot Ya",
        artist: "Notorious BIG",
        Image: "",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/B.I.G.+-+Who+Shot+Ya.mp3",
      },
      {
        id: 45783,
        name: "Bleed II",
        artist: "Notorious BIG",
        Image: "",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/The+Notorious+B.I.G+-+Niggas+Bleed+II.mp3"
      },
      {
        id: 45785,
        name: "Sideways",
        artist: "2Pac Notorious BIG",
        Image: "",
        number: "4",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/Biggie+%26+2Pac+-+Sideways.mp3"
      },
      {
        id: 45786,
        name: "Runnin'",
        artist: "Notorious BIG",
        Image: "",
        number: "5",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/The+Notorious+B.I.G.+ft.+2Pac+-+Runnin'.mp3"
      },
      {
        id: 45787,
        name: "Psychos",
        artist: "Notorious BIG",
        Image: "",
        number: "6",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/2Pac+%26+Biggie+-+Psychos.mp3"
      },
      {
        id: 45788,
        name: "a day in the life of a fool",
        artist: "Notorious BIG",
        Image: "",
        number: "7",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/Notorious+BIG+-+A+Day+in+the+Life+of+a+Fool.mp3"
      },
      {
        id: 45789,
        name: "dolya",
        artist: "Notorious BIG",
        Image: "",
        number: "8",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/streets/Dolya+Vorovskaya.mp3"
      },
    ],
  },
  {
    name: "Coming of Age 2",
    id: 178942,
    Image: "Natela.jpg",
    songlist: [
      {
        id: 13491,
        name: "TightRope",
        artist: "xxxTentacion",
        Image: "https://i.imgur.com/pkVwrqH.jpg",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/XXXTENTACION+-+Tightrope.mp3",
      },
    ],
    songlist2: [
      {
        id: 13893,
        name: "test and recognize",
        artist: "s",
        Image: "https://i.imgur.com/pkVwrqH.jpg",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/seekae+-+test+%26+recognize.mp3",
      },
      {
        id: 13892,
        name: "Funeral Of Our Fire!",
        artist: "s",
        Image: "https://i.imgur.com/pkVwrqH.jpg",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Shadden+Fahim+-+Funeral+Of+Our+Fire.mp3",
      },
      {
        id: 13801,
        name: "Summer Bummer ft.",
        artist: "Lana Del Rey & A$AP Rocky",
        Image: "https://i.imgur.com/pkVwrqH.jpg",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Lana+Del+Rey+-+Summer+Bummer+ft..mp3",
      },
      {
        id: 13891,
        name: "You Are My High",
        artist: "Snake",
        Image: "https://i.imgur.com/pkVwrqH.jpg",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/You+Are+My+High.mp3",
      },
      {
        id: 13890,
        name: "Trop Beau",
        artist: "Emma Peters",
        Image: "",
        number: "4",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Lomepal+-+Trop+Beau.mp3",
      },
    ],
  },
  {
    name: "Coming of Age",
    id: 178941,
    Image: "blacktbilisi.jfif",
    songlist: [
      {
        id: 17892,
        name: "No Church In The Wild",
        artist: "Jay Z - Kanye West",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kanye+West+-+No+Church+In+The+Wild.mp3",
      },
      {
        id: 17891,
        name: "Otis Redding",
        artist: "JAY Z, Kanye West",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/JAY+Z%2C+Kanye+West+-+Otis+Redding.mp3",
      },
      {
        id: 17893,
        name: "Brigada",
        artist: "Pchola Kosmos Fly",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Brigada+++Pchola+%2C+Kosmos+%2C+Fily+Songs.mp3"
      },
      {
        id: 17894,
        name: "The Story of",
        artist: "JAY Z",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "4",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/JAY-Z+-+The+Story+of+O.J.mp3",
      },
      {
        id: 17895,
        name: "JD",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "5",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/A%24AP+ROCKY+-+JD.mp3",
      },
      {
        id: 17896,
        name: "Multiply",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "6",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/A%24AP+Rocky+-+Multiply.mp3",
      },
      {
        id: 17897,
        name: "King's Dead",
        artist: "JAY Z, Future",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "7",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/King's+Dead.mp3",
      },
      {
        id: 17898,
        name: "Love$ick",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "8",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Mura+Masa+-+Love%24ick+ft.+A%24AP+Rocky.mp3",
      },
      {
        id: 17899,
        name: "Angels",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "9",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/A%24AP+Rocky+-+Angels.mp3",
      },
      {
        id: 178910,
        name: "Praise The Lord",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "10",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/A%24AP+Rocky+-+Praise+The+Lord.mp3",
      },
      {
        id: 178911,
        name: "Sundress",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "11",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/A%24AP+Rocky+-+Sundress.mp3",
      },
      {
        id: 178912,
        name: "Babushka Boi",
        artist: "A$AP Rocky",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "12",
        URL: "",
      },
      {
        id: 178913,
        name: "Location",
        artist: "Playboi Carti",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "13",
        URL: "",
      },
      {
        id: 178914,
        name: "Molly",
        artist: "Playboi Carti",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "14",
        URL: "",
      },
      {
        id: 178915,
        name: "Cult Classic",
        artist: "Playboi Carti",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "15",
        URL: "",
      },
      {
        id: 178916,
        name: "M.A.A.D City",
        artist: "Kendrick Lamar",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "16",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kendrick+Lamar+-+M.A.A.D.+City.mp3",
      },
      {
        id: 178917,
        name: "Alright",
        artist: "Kendrick Lamar",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "17",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kendrick+Lamar+-+Alright.mp3",
      },
      {
        id: 178918,
        name: "Lust",
        artist: "Kendrick Lamar",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "18",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kendrick+Lamar+-+LUST.mp3",
      },
      {
        id: 178919,
        name: "Fear",
        artist: "Kendrick Lamar",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "19",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kendrick+Lamar+-+Fear.mp3",
      },
      {
        id: 178920,
        name: "Sing About me, I'm Dying of Thirst",
        artist: "Kendrick Lamar",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "20",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kendrick+Lamar+-+Sing+About+Me%2C+I'm+Dying+Of+Thirst.mp3",
      },
      {
        id: 178921,
        name: "Can't Tell Me Nothing",
        artist: "Kanye West",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "21",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Can't+Tell+Me+Nothing.mp3",
      },
      {
        id: 178922,
        name: "Clique",
        artist: "Kanye West",
        Image: "https://i.imgur.com/645WVY5.jpg",
        number: "22",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/age/Kanye+West+-+Clique+ft.+Big+Sean+%26+Jay-Z.mp3",
      },

    ],
  },
];
