import { Playlist } from "./components/hooks/types";

export const playlists: Playlist[] = [
  {
    name: "Sorry )) It'$ too Late",
    id: 454036,
    Image: "2pac.jpg",
    songlist: [
      {
        id: 45401,
        name: "Suicidal Thoughts",
        artist: "2Pac",
        Image: "2pac.jpg",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/2PAC+-+Suicidal+Thoughts.mp3",
      },
      {
        id: 45402,
        name: "Black Cotton _ Realest Killaz",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "2",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/Black+Cotton+-+2pac.mp3",
      },
      {
        id: 45403,
        name: "Don't Go To Sleep",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "3",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/Don't+Go+To+Sleep+-+2pac.mp3",
      },
      {
        id: 45404,
        name: "Dumping this Life I lead",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "4",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/Dumpin+x+This+life+i+lead+-+2Pac.mp3",
      },
      {
        id: 45405,
        name: "Havoc-Thug Chroniles",
        artist: "Mobb Deep & Kool-G",
        Image: "2pac.jpg",
        number: "5",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/sorry/Havoc-Thug+Chroniles.mp3",
      },
    ],
  },
  {
    name: "Diamond Off Streets",
    id: 457897,
    Image: "playboicarti.jpg",
    songlist: [
      {
        id: 45781,
        name: "Dear Mama",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "1",
        URL: "",
      },
      {
        id: 45782,
        name: "Changes",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "2",
        URL: "",
      },
    ],
  },
  {
    name: "ἀναγνώρισις",
    id: 947345,
    Image: "techno.jpg",
    songlist: [
      {
        id: 94731,
        name: "Light",
        artist: "Death Note",
        Image: "2pac.jpg",
        number: "1",
        URL: "https://audioplayernikkodev.s3.eu-west-3.amazonaws.com/songs/moments/Death+Note+-+Light's+Theme.mp3",
      },
      {
        id: 94732,
        name: "Mellow A",
        artist: "Death note",
        Image: "2pac.jpg",
        number: "2",
        URL: "",
      },
    ],
  },
  {
    name: "",
    id: 795415,
    Image: "heart.jpg",
    songlist: [
      {
        id: 79541,
        name: "Dear Mama",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "1",
        URL: "",
      },
      {
        id: 79542,
        name: "Changes",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "2",
        URL: "",
      },
    ],
  },
  {
    name: "Coming of Age",
    id: 178941,
    Image: "blacktbilisi.jfif",
    songlist: [
      {
        id: 17891,
        name: "Dear Mama",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "1",
        URL: "",
      },
      {
        id: 17892,
        name: "Changes",
        artist: "2pac",
        Image: "2pac.jpg",
        number: "2",
        URL: "",
      },
    ],
  },
];
